### ISSUE TITLE
.2 misreported in WP plugins page as .1, fetches update, puts in trunk folder for 2 instances of plugin in the same folder

### ISSUE THREAD

**Issue by Halle** [seanvoss/striper#2]
Hi Sean,

Thank you very much for providing this plugin. I installed the latest .2 version from this repo, and my WP install reports it as .1 and tells me there is a .2 update available. If I allow it to fetch the .2 update, a "Trunk" directory is added to the plugin directory and the entire .2 file structure is replicated in that directory. Then when I ask WP to uninstall the plugin, in its "do you really want to do this?" warning it reports that I am asking to uninstall 3 plugins, all of which are called "Striper". Seems to just be some kind of recursion issue, wanted to let you know about it. My workaround is to just not let WP handle the updating, so this isn't a serious issue for me.

**Comment by seanvoss** [comment]
Hey Halle,

I'm sorry this took me so long to get back to you, i've been focusing on the bug reports on the Wordpress Forums.

I've updated the code here to v0.8 which is nicely stable, what you are speaking of I think is correct, just keep your plugin updated over there. I have a few smaller fixes which make the one on wordpress a bit newer at 0.12.

Cheers,

Sean
