### ISSUE TITLE
Bug in handling of Stripe publishable keys?

### ISSUE THREAD

**Issue by daigo75** [seanvoss/striper#4]
File: `stripe_gateway.php`
## Current code

```
$this->testPublishableKey = $this->settings['test_publishable_key'  ];
$this->livePublishableKey = $this->settings['test_publishable_key'  ];
```
## Correct code (I reckon)

```
$this->testPublishableKey = $this->settings['test_publishable_key'];
$this->livePublishableKey = $this->settings['live_publishable_key'];
```

**Comment by seanvoss** [comment]
Hey Thanks Daigo, this I believe we worked out on the wordpress forums.

**Comment by daigo75** [comment]
Hi Sean,
That's right. When I reported the bug, I didn't notice that the plugin on Github was v0.1 and that the issue had already been fixed. You can close the bug as resolved.

--- Original Message ---
