### ISSUE TITLE
Wordpress 3.8 Breaks Compatibility

### ISSUE THREAD

**Issue by macconnolly** [seanvoss/striper#5]
After the latest WordPress 3.8 update, the Striper plugin causes a blank white page, site-wide until it is deleted.

**Comment by svoss-trulia** [comment]
Hey macconnolly I actually don't think that was Wordpress 3.8, around the time 3.8 was released I make a patch which broke the plugin for users of PHP < 5.3.

Update to the latest on wordpress and see if that works for you I have a test running on 3.8 just fine.

**Comment by macconnolly** [comment]
Thank you very much. I will give it a shot. Thank you.
