### ISSUE TITLE
Latest Striper version broke my checkout process

### ISSUE THREAD

**Issue by chrismarquardt** [seanvoss/striper#7]
Sean, not sure which channel to contact you on, so I've posted on a few. Feel free to delete my questions on the other channels if this one works best.

Here's the issue: since 0.28 Striper doesn't seem to play nice with other payment plugins anymore. I use Paypal standard and a Bitcoin payment plugin on https://shop.chrismarquardt.com/bookshop/ and since the update, none of the other methods would work. 

The symptom: the "Place order" button seems inactive when I chose anything but Striper. It looks like Striper seems to be called (and reacts with an invalid card number or similar) no matter if Paypal or Bitcoin are selected.

For now I had to disable Striper to allow Paypal and Bitcoin payments to go through.

Any idea?

**Comment by svoss-trulia** [comment]
Hey Chris,

I applaud your efforts to get in touch with me, it should already by fixed in the latest version.

**Comment by chrismarquardt** [comment]
Awesome, thanks for the quick turn-around! Just tried to buy Striper from your but both PayPal and Credit Card checkout wouldn't work. The first one was declined, the second one said it was in test mode. Dude, this way you'll never get rich. Any other way to give you a donation?

**Comment by seanvoss** [comment]
Took Striper out of demo mode, I end up having it there often as I'm always updating for some reason or another.

**Comment by chrismarquardt** [comment]
Sent you the donation, thanks again :)
